id: ID6794866
legacy_id: P010791
ocr_import_info:
  bdrc_scan_id: W8LS17934
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:18:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:04:01.989957+00:00'
last_modified: 2022-09-04 12:04:54.477999
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17934
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17934
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟ་ནག་རྣམ་འགྲེལ། ལེའུ་དང་པོ།
  author: རྟ་ནག་པ་དགེ་འདུན་བློ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.6444405277415666
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I8LS17949:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17949
      total_pages: 1446
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17949.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6444405277415666
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
