id: P010791
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17934
  title: རྟ་ནག་རྣམ་འགྲེལ། ལེའུ་དང་པོ།
  author: ''
  volumes:
    778d444dc363404fb64bfeffeb9ac018:
      image_group_id: I8LS17949
      title: ''
      volume_number: 1
      total_pages: 1446
      base_file: v001.txt
